name: React CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v3

      # 2. Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies
      - run: npm install

      # 4. Run tests (if you have any)
      - run: npm test || echo "No tests found, skipping"

      # 5. Build the app
      - run: npm run build

  docker-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - uses: actions/checkout@v3

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t react-app:latest .

      # Optional: push to Docker Hub (requires secrets)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker tag react-app:latest ${{ secrets.DOCKER_USERNAME }}/react-app:latest && \
             docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest
